metadata:
  labels:
    hystrix.enabled: true
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: hystrix
      port: 8080
      protocol: TCP
      targetPort: 8080